name: missing_kotlin
description: Missing Kotlin methods ? let / run / also / takeIf / when / if ? try this awesome repository
version: 0.0.1
author: Florent Champigny <champigny.florent@gmail.com>
homepage: https://github.com/florent37/Missing_Kotlin

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
